"use client";

import { BarChart3, BrainCircuit, Clock, PieChart, Star } from "lucide-react";
import { BarChart, Donut, HBars, LineChart } from "@/components/charts";
import { Card, CardHeader } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { SectionHeader } from "@/components/ui/Misc";
import { globalStats, muniPerformance, monthlyReports, priorityResolution, categoryDist, satisfactionByMonth, statusCounts } from "@/lib/selectors";
import { useApp } from "@/lib/store";
import { fmtRelative } from "@/lib/format";
import { MOCK_NOW } from "@/lib/mock/data";

export default function AdminAnalyticsPage() {
  const db = useApp();
  const stats = globalStats(db.cases);
  const trend = monthlyReports(db.cases);
  const cats = categoryDist(db.cases);
  const statuses = statusCounts(db.cases);
  const byPriority = priorityResolution(db.cases);
  const perf = muniPerformance(db);
  const satisfaction = satisfactionByMonth(db.cases);

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Global analytics"
        subtitle="Platform-wide intelligence — trends, categories, SLA performance and AI insights"
      />

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader title="Monthly trend" subtitle="reports vs closed" icon={BarChart3} />
          <div className="px-4 py-4">
            <LineChart
              labels={trend.map((t) => t.month)}
              series={[
                { name: "Reports", color: "#2563eb", values: trend.map((t) => t.count) },
                { name: "Closed", color: "#10b981", values: trend.map((t) => t.resolved) },
              ]}
            />
          </div>
        </Card>

        <Card>
          <CardHeader title="Category distribution" subtitle="all reports" icon={PieChart} />
          <div className="px-4 py-6">
            <Donut data={cats.slice(0, 6)} centerValue={stats.total} centerLabel="reports" />
          </div>
        </Card>

        <Card>
          <CardHeader title="Pipeline by status" subtitle="case lifecycle funnel" icon={Clock} />
          <div className="px-4 py-4">
            <BarChart
              data={statuses.map((s) => ({
                label: s.label,
                value: s.value,
                color: s.key === "CLOSED" ? "#10b981" : s.key === "REJECTED" || s.key === "REOPENED" ? "#f43f5e" : "#2563eb",
              }))}
            />
          </div>
        </Card>

        <Card>
          <CardHeader title="Avg resolution by priority" subtitle="hours, resolved cases" icon={Clock} />
          <div className="px-4 py-4">
            <BarChart
              data={byPriority.map((p) => ({
                label: p.label,
                value: p.value,
                color: p.priority === "CRITICAL" ? "#f43f5e" : p.priority === "HIGH" ? "#f97316" : p.priority === "MEDIUM" ? "#f59e0b" : "#94a3b8",
              }))}
              suffix="h"
            />
            <p className="mt-2 text-[11px] text-slate-400">
              SLA targets: CRITICAL 4h · HIGH 24h · MEDIUM 72h · LOW 168h
            </p>
          </div>
        </Card>

        <Card>
          <CardHeader title="Citizen satisfaction" subtitle="avg rating by month" icon={Star} />
          <div className="px-4 py-4">
            <LineChart
              labels={satisfaction.map((s) => s.month)}
              series={[{ name: "Rating", color: "#14b8a6", values: satisfaction.map((s) => s.value || 0) }]}
            />
          </div>
        </Card>

        <Card>
          <CardHeader title="Municipality SLA compliance" subtitle="resolved within SLA" icon={BarChart3} />
          <div className="px-5 py-5">
            <HBars
              data={perf.map((p) => ({
                label: p.municipality.shortName,
                value: Math.round(p.sla.compliance * 100),
                color: p.sla.compliance > 0.8 ? "#10b981" : "#f59e0b",
                hint: `${p.sla.breached} breaches`,
              }))}
              suffix="%"
            />
          </div>
        </Card>
      </div>

      <Card>
        <CardHeader
          title="AI insight feed"
          subtitle="generated by the intelligence service (Member 3) — advisory only"
          icon={BrainCircuit}
        />
        <div className="divide-y divide-slate-100">
          {db.insights.map((i) => (
            <div key={i.id} className="flex gap-4 px-5 py-4">
              <Badge className="mt-0.5 shrink-0 border-violet-200 bg-violet-50 text-violet-700">
                {i.type.replaceAll("_", " ").toLowerCase()}
              </Badge>
              <div className="min-w-0">
                <p className="text-sm font-semibold text-slate-900">{i.title}</p>
                <p className="mt-1 text-xs leading-relaxed text-slate-500">{i.body}</p>
                <p className="mt-1.5 text-[10px] text-slate-400">
                  {Math.round(i.confidence * 100)}% confidence · {fmtRelative(i.at, MOCK_NOW)}
                </p>
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
