"use client";

import Link from "next/link";
import {
  BrainCircuit,
  Copy,
  Lightbulb,
  MapPinned,
  ShieldAlert,
  Timer,
  TrendingUp,
} from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Card, CardHeader } from "@/components/ui/Card";
import { InfoNote, SectionHeader } from "@/components/ui/Misc";
import { fmtRelative } from "@/lib/format";
import { MOCK_NOW } from "@/lib/mock/data";
import { useApp } from "@/lib/store";
import type { InsightType } from "@/lib/types";

const TYPE_META: Record<InsightType, { icon: typeof TrendingUp; cls: string; label: string }> = {
  SPIKE: { icon: TrendingUp, cls: "border-rose-200 bg-rose-50 text-rose-700", label: "spike" },
  DUPLICATE_CLUSTER: { icon: Copy, cls: "border-teal-200 bg-teal-50 text-teal-700", label: "duplicate cluster" },
  RISK_ANOMALY: { icon: ShieldAlert, cls: "border-amber-200 bg-amber-50 text-amber-700", label: "risk anomaly" },
  SLA_WARNING: { icon: Timer, cls: "border-orange-200 bg-orange-50 text-orange-700", label: "sla warning" },
  RECOMMENDATION: { icon: Lightbulb, cls: "border-blue-200 bg-blue-50 text-blue-700", label: "recommendation" },
  HOTSPOT_ALERT: { icon: MapPinned, cls: "border-violet-200 bg-violet-50 text-violet-700", label: "hotspot alert" },
};

export default function AiInsightsPage() {
  const { insights, activeMunicipalityId: mid } = useApp();
  const list = insights.filter((i) => !i.municipalityId || i.municipalityId === mid);

  return (
    <div className="space-y-5">
      <SectionHeader
        title="AI insights"
        subtitle="Continuous intelligence on your cases — spikes, duplicates, risk patterns and recommendations"
      />
      <InfoNote tone="violet">
        Generated by the AI service (Member 3) from report streams and history. Every insight carries a confidence
        score; recommendations never execute automatically.
      </InfoNote>

      <div className="grid gap-4 xl:grid-cols-2">
        {list.map((i) => {
          const meta = TYPE_META[i.type];
          const Icon = meta.icon;
          return (
            <Card key={i.id} className="p-5">
              <div className="flex items-start justify-between gap-3">
                <Badge className={meta.cls}>
                  <Icon className="h-3 w-3" /> {meta.label}
                </Badge>
                <span className="shrink-0 text-[10px] text-slate-400">{fmtRelative(i.at, MOCK_NOW)}</span>
              </div>
              <p className="mt-3 text-sm font-bold text-slate-900">{i.title}</p>
              <p className="mt-1.5 text-xs leading-relaxed text-slate-600">{i.body}</p>
              <div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3">
                <span className="flex items-center gap-1 text-[10px] text-slate-400">
                  <BrainCircuit className="h-3 w-3" /> {Math.round(i.confidence * 100)}% confidence
                </span>
                {i.caseId && (
                  <Link href={`/municipality/cases/${i.caseId}`} className="text-xs font-semibold text-blue-600 hover:underline">
                    Open related case →
                  </Link>
                )}
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
